import { Container } from 'inversify';
import { IUserRepository } from './Interfaces/Repository/i-user-repositry';
import { UserRepository } from './repositories/user-repository';
import { IAdminRepository } from './Interfaces/Repository/i-admin-repositry';
import { AdminRepository } from './repositories/admin-dashboard-repository';
import { ICallLogRepository } from './Interfaces/Repository/i-call-repositry';
import { CallLogRepository } from './repositories/call-repository';
import { ICategoryRepository } from './Interfaces/Repository/i-category-repositry';
import { CategoryRepository } from './repositories/category-repository';
import { IChatRepository } from './Interfaces/Repository/i-chat-repositry';
import { ChatRepository } from './repositories/chat-repository';
import { ICollaborationRepository } from './Interfaces/Repository/i-collaboration-repositry';
import { CollaborationRepository } from './repositories/collaboration-repository';
import { IContactMessageRepository } from './Interfaces/Repository/i-contact-message-repositry';
import { ContactMessageRepository } from './repositories/contact-us-repository';
import { IContactRepository } from './Interfaces/Repository/i-contact-repositry';
import { ContactRepository } from './repositories/contact-repository';
import { IFeedbackRepository } from './Interfaces/Repository/i-feedback-repositry';
import { FeedbackRepository } from './repositories/feedback-repository';
import { IGroupRepository } from './Interfaces/Repository/i-group-repositry';
import { GroupRepository } from './repositories/group-repository';
import { IMentorRepository } from './Interfaces/Repository/i-mentor-repositry';
import { MentorRepository } from './repositories/mentor-repository';
import { INotificationRepository } from './Interfaces/Repository/i-notification-repositry';
import { NotificationRepository } from './repositories/notification-repository';
import { IReviewRepository } from './Interfaces/Repository/i-review-repositry';
import { ReviewRepository } from './repositories/review-repository';
import { ISkillsRepository } from './Interfaces/Repository/i-skills-repositry';
import { SkillsRepository } from './repositories/skills-repository';
import { ISubcategoryRepository } from './Interfaces/Repository/i-sub-category-repositry';
import { SubcategoryRepository } from './repositories/sub-category-repository';
import { ITaskRepository } from './Interfaces/Repository/i-task-repositry';
import { TaskRepository } from './repositories/task-repository';
import { IUserConnectionRepository } from './Interfaces/Repository/i-user-collaboration-repositry';
import { UserConnectionRepository } from './repositories/user-collaboration-repository';
import { IAuthService } from './Interfaces/Services/i-user-service';
import { AuthService } from './services/auth-service';
import { IJWTService } from './Interfaces/Services/i-jwt-service';
import { JWTServiceClass } from './Utils/utils/auth-utils/j-w-t';
import { IAdminService } from './Interfaces/Services/i-admin-service';
import { AdminService } from './services/admin-dashboard-service';
import { ICallService } from './Interfaces/Services/i-call-service';
import { CallService } from './services/call-service';
import { ICategoryService } from './Interfaces/Services/i-category-service';
import { CategoryService } from './services/category-service';
import { IChatService } from './Interfaces/Services/i-chat-service';
import { ChatService } from './services/chat-service';
import { ICollaborationService } from './Interfaces/Services/i-collaboration-service';
import { CollaborationService } from './services/collaboration-service';
import { IContactMessageService } from './Interfaces/Services/i-contact-message-service';
import { ContactMessageService } from './services/contact-us-service';
import { IContactService } from './Interfaces/Services/i-contact-service';
import { ContactService } from './services/contact-service';
import { IFeedbackService } from './Interfaces/Services/i-feedback-service';
import { FeedbackService } from './services/feedback-service';
import { IGroupService } from './Interfaces/Services/i-group-service';
import { GroupService } from './services/group-service';
import { IMentorService } from './Interfaces/Services/i-mentor-service';
import { MentorService } from './services/mentor-service';
import { INotificationService } from './Interfaces/Services/i-notification-service';
import { NotificationService } from './services/notification-service';
import { IReviewService } from './Interfaces/Services/i-review-service';
import { ReviewService } from './services/review-service';
import { ISkillsService } from './Interfaces/Services/i-skills-service';
import { SkillsService } from './services/skill-service';
import { ISubcategoryService } from './Interfaces/Services/i-sub-category-service';
import { SubcategoryService } from './services/sub-category-service';
import { ITaskService } from './Interfaces/Services/i-task-service';
import { TaskService } from './services/task-service';
import { IUserConnectionService } from './Interfaces/Services/i-user-collaboration-service';
import { UserConnectionService } from './services/user-collaboartion-service';
import { IAuthMiddleware } from './Interfaces/Middleware/i-auth-middleware';
import { AuthMiddleware } from './middlewares/auth-middleware';
import { IAdminController } from './Interfaces/Controller/i-admin-controller';
import { AdminController } from './controllers/admin-dashboard-controller';
import { IAuthController } from './Interfaces/Controller/i-auth-controller';
import { AuthController } from './controllers/auth-controller';
import { ICallController } from './Interfaces/Controller/i-call-controller';
import { CallController } from './controllers/call-controller';
import { ICategoryController } from './Interfaces/Controller/i-category-controller';
import { CategoryController } from './controllers/category-controller';
import { IChatController } from './Interfaces/Controller/i-chat-controller';
import { ChatController } from './controllers/chat-controller';
import { ICollaborationController } from './Interfaces/Controller/i-collaboration-controller';
import { CollaborationController } from './controllers/collaboration-controller';
import { IContactController } from './Interfaces/Controller/i-contact-controller';
import { ContactController } from './controllers/contact-controller';
import { IContactMessageController } from './Interfaces/Controller/i-contact-us-controller';
import { ContactMessageController } from './controllers/contactUs-controller';
import { IFeedbackController } from './Interfaces/Controller/i-feedBack-controller';
import { FeedbackController } from './controllers/feedBack-controller';
import { IGroupController } from './Interfaces/Controller/i-group-controller';
import { GroupController } from './controllers/group-controller';
import { IMentorController } from './Interfaces/Controller/i-mentor-controller';
import { MentorController } from './controllers/mentor-controller';
import { INotificationController } from './Interfaces/Controller/i-notification-controller';
import { NotificationController } from './controllers/notification-controller';
import { IReviewController } from './Interfaces/Controller/i-review-controller';
import { ReviewController } from './controllers/review-controller';
import { ISkillsController } from './Interfaces/Controller/i-skills-controller';
import { SkillsController } from './controllers/skills-controller';
import { ISubcategoryController } from './Interfaces/Controller/i-sub-category-controller';
import { SubcategoryController } from './controllers/subCategory-controller';
import { ITaskController } from './Interfaces/Controller/i-task-controller';
import { TaskController } from './controllers/task-controller';
import { IUserConnectionController } from './Interfaces/Controller/i-user-collaboration-controller';
import { UserConnectionController } from './controllers/user-collaboration-controller';
import { ISocketService } from './Interfaces/Services/i-socket-service';
import { SocketService } from './socket/socket-service';
import { IChatSocketHandler } from './Interfaces/Services/i-chat-socket-handler';
import { ChatSocketHandler } from './socket/chat-socket-handler';
import { ICallSocketHandler } from './Interfaces/Services/i-call-socket-handler';
import { CallSocketHandler } from './socket/call-socket-handler';
import { IGroupCallSocketHandler } from './Interfaces/Services/i-group-call-socket-handler';
import { GroupCallSocketHandler } from './socket/group-call-socket-handler';
import { INotificationSocketHandler } from './Interfaces/Services/i-notification-socket-handler';
import { NotificationSocketHandler } from './socket/notification-socket-handler';
import { IMentorExperienceRepository } from './Interfaces/Repository/i-mentor-experience-repository';
import { MentorExperienceRepository } from './repositories/mentor-experience-repository';


const container = new Container();

// Bind Interface to Repositries
container.bind<IUserRepository>('IUserRepository').to(UserRepository);
container.bind<IAdminRepository>('IAdminRepository').to(AdminRepository);
container.bind<ICallLogRepository>('ICallLogRepository').to(CallLogRepository);
container.bind<ICategoryRepository>('ICategoryRepository').to(CategoryRepository);
container.bind<IChatRepository>('IChatRepository').to(ChatRepository);
container.bind<ICollaborationRepository>('ICollaborationRepository').to(CollaborationRepository);
container.bind<IContactMessageRepository>('IContactMessageRepository').to(ContactMessageRepository);
container.bind<IContactRepository>('IContactRepository').to(ContactRepository);
container.bind<IFeedbackRepository>('IFeedbackRepository').to(FeedbackRepository);
container.bind<IGroupRepository>('IGroupRepository').to(GroupRepository);
container.bind<IMentorRepository>('IMentorRepository').to(MentorRepository);
container.bind<INotificationRepository>('INotificationRepository').to(NotificationRepository);
container.bind<IReviewRepository>('IReviewRepository').to(ReviewRepository);
container.bind<ISkillsRepository>('ISkillsRepository').to(SkillsRepository);
container.bind<ISubcategoryRepository>('ISubCategoryRepository').to(SubcategoryRepository);
container.bind<ITaskRepository>('ITaskRepository').to(TaskRepository);
container.bind<IUserConnectionRepository>('IUserConnectionRepository').to(UserConnectionRepository);
container.bind<IMentorExperienceRepository>("IMentorExperienceRepository").to(MentorExperienceRepository);


//Bind Interface to Services
container.bind<IAuthService>('IUserService').to(AuthService);
container.bind<IJWTService>('IJWTService').to(JWTServiceClass);
container.bind<IAdminService>('IAdminService').to(AdminService);
container.bind<ICallService>('ICallService').to(CallService);
container.bind<ICategoryService>('ICategoryService').to(CategoryService);
container.bind<IChatService>('IChatService').to(ChatService);
container.bind<ICollaborationService>('ICollaborationService').to(CollaborationService);
container.bind<IContactMessageService>('IContactMessageService').to(ContactMessageService);
container.bind<IContactService>('IContactService').to(ContactService);
container.bind<IFeedbackService>('IFeedbackService').to(FeedbackService);
container.bind<IGroupService>('IGroupService').to(GroupService);
container.bind<IMentorService>('IMentorService').to(MentorService);
container.bind<INotificationService>('INotificationService').to(NotificationService);
container.bind<IReviewService>('IReviewService').to(ReviewService);
container.bind<ISkillsService>('ISkillsService').to(SkillsService);
container.bind<ISubcategoryService>('ISubCategoryService').to(SubcategoryService);
container.bind<ITaskService>('ITaskService').to(TaskService);
container.bind<IUserConnectionService>('IUserConnectionService').to(UserConnectionService);

//Middlewares
container.bind<IAuthMiddleware>('IAuthMiddleware').to(AuthMiddleware);

// Bind socket-related classes
container.bind<ISocketService>('ISocketService').to(SocketService);
container.bind<IChatSocketHandler>('IChatSocketHandler').to(ChatSocketHandler);
container.bind<ICallSocketHandler>('ICallSocketHandler').to(CallSocketHandler);
container.bind<IGroupCallSocketHandler>('IGroupCallSocketHandler').to(GroupCallSocketHandler);
container.bind<INotificationSocketHandler>('INotificationSocketHandler').to(NotificationSocketHandler);

//Bind Interface to the controllers
container.bind<IAdminController>('IAdminController').to(AdminController);
container.bind<IAuthController>('IAuthController').to(AuthController);
container.bind<ICallController>('ICallController').to(CallController);
container.bind<ICategoryController>('ICategoryController').to(CategoryController);
container.bind<IChatController>('IChatController').to(ChatController);
container.bind<ICollaborationController>('ICollaborationController').to(CollaborationController);
container.bind<IContactController>('IContactController').to(ContactController);
container.bind<IContactMessageController>('IContactMessageController').to(ContactMessageController);
container.bind<IFeedbackController>('IFeedBackController').to(FeedbackController);
container.bind<IGroupController>('IGroupController').to(GroupController);
container.bind<IMentorController>('IMentorController').to(MentorController);
container.bind<INotificationController>('INotificationController').to(NotificationController);
container.bind<IReviewController>('IReviewController').to(ReviewController);
container.bind<ISkillsController>('ISkillsController').to(SkillsController);
container.bind<ISubcategoryController>('ISubCategoryController').to(SubcategoryController);
container.bind<ITaskController>('ITaskController').to(TaskController);
container.bind<IUserConnectionController>('IUserConnectionController').to(UserConnectionController);


export default container;

