import { Container } from 'inversify';
import { IUserRepository } from './Interfaces/Repository/IUserRepository';
import { UserRepository } from './Repositories/User.repository';
import { IAdminRepository } from './Interfaces/Repository/IAdminRepositry';
import { AdminRepository } from './Repositories/AdminDashboard.repository';
import { ICallLogRepository } from './Interfaces/Repository/ICallRepositry';
import { CallLogRepository } from './Repositories/Call.repository';
import { ICategoryRepository } from './Interfaces/Repository/ICategoryRepository';
import { CategoryRepository } from './Repositories/Category.repository';
import { IChatRepository } from './Interfaces/Repository/IChatRepository';
import { ChatRepository } from './Repositories/Chat.repository';
import { ICollaborationRepository } from './Interfaces/Repository/ICollaborationRepository';
import { CollaborationRepository } from './Repositories/Collaboration.repository';
import { IContactMessageRepository } from './Interfaces/Repository/IContactMessageRepository';
import { ContactMessageRepository } from './Repositories/ContactUs.repository';
import { IContactRepository } from './Interfaces/Repository/IContactRepository';
import { ContactRepository } from './Repositories/Contact.repository';
import { IFeedbackRepository } from './Interfaces/Repository/IFeedbackRepository';
import { FeedbackRepository } from './Repositories/FeedBack.repository';
import { IGroupRepository } from './Interfaces/Repository/IGroupRepository';
import { GroupRepository } from './Repositories/Group.repository';
import { IMentorRepository } from './Interfaces/Repository/IMentorRepository';
import { MentorRepository } from './Repositories/Mentor.repository';
import { INotificationRepository } from './Interfaces/Repository/INotificationRepository';
import { NotificationRepository } from './Repositories/Notification.repository';
import { IReviewRepository } from './Interfaces/Repository/IReviewRepository';
import { ReviewRepository } from './Repositories/Review.repository';
import { ISkillsRepository } from './Interfaces/Repository/ISkillsRepository';
import { SkillsRepository } from './Repositories/Skills.repository';
import { ISubcategoryRepository } from './Interfaces/Repository/ISubCategoryRepository';
import { SubcategoryRepository } from './Repositories/SubCategory.repository';
import { ITaskRepository } from './Interfaces/Repository/ITaskRepository';
import { TaskRepository } from './Repositories/Task.repository';
import { IUserConnectionRepository } from './Interfaces/Repository/IUserCollaborationRepository';
import { UserConnectionRepository } from './Repositories/UserCollaboration.repository';
import { IAuthService } from './Interfaces/Services/IUserService';
import { AuthService } from './Services/Auth.service';
import { IJWTService } from './Interfaces/Services/IJWTService';
import { JWTServiceClass } from './Utils/Utils/Auth.utils/JWT';
import { IAdminService } from './Interfaces/Services/IAdminService';
import { AdminService } from './Services/AdminDashboard.service';
import { ICallService } from './Interfaces/Services/ICallService';
import { CallService } from './Services/Call.service';
import { ICategoryService } from './Interfaces/Services/ICategoryService';
import { CategoryService } from './Services/Category.service';
import { IChatService } from './Interfaces/Services/IChatService';
import { ChatService } from './Services/Chat.service';
import { ICollaborationService } from './Interfaces/Services/ICollaborationService';
import { CollaborationService } from './Services/Collaboration.service';
import { IContactMessageService } from './Interfaces/Services/IContactMessageService';
import { ContactMessageService } from './Services/ContactUs.service';
import { IContactService } from './Interfaces/Services/IContactService';
import { ContactService } from './Services/Contact.service';
import { IFeedbackService } from './Interfaces/Services/IFeedbackService';
import { FeedbackService } from './Services/Feedback.service';
import { IGroupService } from './Interfaces/Services/IGroupService';
import { GroupService } from './Services/Group.service';
import { IMentorService } from './Interfaces/Services/IMentorService';
import { MentorService } from './Services/Mentor.service';
import { INotificationService } from './Interfaces/Services/INotificationService';
import { NotificationService } from './Services/Notification.service';
import { IReviewService } from './Interfaces/Services/IReviewService';
import { ReviewService } from './Services/Review.service';
import { ISkillsService } from './Interfaces/Services/ISkillsService';
import { SkillsService } from './Services/Skill.service';
import { ISubcategoryService } from './Interfaces/Services/ISubCategoryService';
import { SubcategoryService } from './Services/SubCategory.service';
import { ITaskService } from './Interfaces/Services/ITaskService';
import { TaskService } from './Services/Task.service';
import { IUserConnectionService } from './Interfaces/Services/IUserCollaborationService';
import { UserConnectionService } from './Services/UserCollaboartion.service';
import { IAuthMiddleware } from './Interfaces/Middleware/IAuthMiddleware';
import { AuthMiddleware } from './middlewares/auth.middleware';
import { IAdminController } from './Interfaces/Controller/IAdminController';
import { AdminController } from './Controllers/AdminDashboard.controller';
import { IAuthController } from './Interfaces/Controller/IAuthController';
import { AuthController } from './Controllers/Auth.controller';
import { ICallController } from './Interfaces/Controller/ICallController';
import { CallController } from './Controllers/Call.controller';
import { ICategoryController } from './Interfaces/Controller/ICategoryController';
import { CategoryController } from './Controllers/Category.controller';
import { IChatController } from './Interfaces/Controller/IChatController';
import { ChatController } from './Controllers/Chat.controller';
import { ICollaborationController } from './Interfaces/Controller/ICollaborationController';
import { CollaborationController } from './Controllers/Collaboration.controller';
import { IContactController } from './Interfaces/Controller/IContactController';
import { ContactController } from './Controllers/Contact.controller';
import { IContactMessageController } from './Interfaces/Controller/IContactUsController';
import { ContactMessageController } from './Controllers/ContactUs.controller';
import { IFeedbackController } from './Interfaces/Controller/IFeedBackController';
import { FeedbackController } from './Controllers/FeedBack.controller';
import { IGroupController } from './Interfaces/Controller/IGroupController';
import { GroupController } from './Controllers/Group.controller';
import { IMentorController } from './Interfaces/Controller/IMentorController';
import { MentorController } from './Controllers/Mentor.controller';
import { INotificationController } from './Interfaces/Controller/INotificationController';
import { NotificationController } from './Controllers/Notification.controller';
import { IReviewController } from './Interfaces/Controller/IReviewController';
import { ReviewController } from './Controllers/Review.controller';
import { ISkillsController } from './Interfaces/Controller/ISkillsController';
import { SkillsController } from './Controllers/Skills.controller';
import { ISubcategoryController } from './Interfaces/Controller/ISubCategoryController';
import { SubcategoryController } from './Controllers/SubCategory.controller';
import { ITaskController } from './Interfaces/Controller/ITaskController';
import { TaskController } from './Controllers/Task.controller';
import { IUserConnectionController } from './Interfaces/Controller/IUserCollaborationController';
import { UserConnectionController } from './Controllers/userCollaboration.controller';
import { ISocketService } from './Interfaces/Services/ISocketService';
import { SocketService } from './socket/SocketService';
import { IChatSocketHandler } from './Interfaces/Services/IChatSocketHandler';
import { ChatSocketHandler } from './socket/ChatSocketHandler';
import { ICallSocketHandler } from './Interfaces/Services/ICallSocketHandler';
import { CallSocketHandler } from './socket/CallSocketHandler';
import { IGroupCallSocketHandler } from './Interfaces/Services/IGroupCallSocketHandler';
import { GroupCallSocketHandler } from './socket/GroupCallSocketHandler';
import { INotificationSocketHandler } from './Interfaces/Services/INotificationSocketHandler';
import { NotificationSocketHandler } from './socket/NotificationSocketHandler';


const container = new Container();

// Bind Interface to Repositries
container.bind<IUserRepository>('IUserRepository').to(UserRepository);
container.bind<IAdminRepository>('IAdminRepository').to(AdminRepository);
container.bind<ICallLogRepository>('ICallLogRepository').to(CallLogRepository);
container.bind<ICategoryRepository>('ICategoryRepository').to(CategoryRepository);
container.bind<IChatRepository>('IChatRepository').to(ChatRepository);
container.bind<ICollaborationRepository>('ICollaborationRepository').to(CollaborationRepository);
container.bind<IContactMessageRepository>('IContactMessageRepository').to(ContactMessageRepository);
container.bind<IContactRepository>('IContactRepository').to(ContactRepository);
container.bind<IFeedbackRepository>('IFeedbackRepository').to(FeedbackRepository);
container.bind<IGroupRepository>('IGroupRepository').to(GroupRepository);
container.bind<IMentorRepository>('IMentorRepository').to(MentorRepository);
container.bind<INotificationRepository>('INotificationRepository').to(NotificationRepository);
container.bind<IReviewRepository>('IReviewRepository').to(ReviewRepository);
container.bind<ISkillsRepository>('ISkillsRepository').to(SkillsRepository);
container.bind<ISubcategoryRepository>('ISubCategoryRepository').to(SubcategoryRepository);
container.bind<ITaskRepository>('ITaskRepository').to(TaskRepository);
container.bind<IUserConnectionRepository>('IUserConnectionRepository').to(UserConnectionRepository);


//Bind Interface to Services
container.bind<IAuthService>('IUserService').to(AuthService);
container.bind<IJWTService>('IJWTService').to(JWTServiceClass);
container.bind<IAdminService>('IAdminService').to(AdminService);
container.bind<ICallService>('ICallService').to(CallService);
container.bind<ICategoryService>('ICategoryService').to(CategoryService);
container.bind<IChatService>('IChatService').to(ChatService);
container.bind<ICollaborationService>('ICollaborationService').to(CollaborationService);
container.bind<IContactMessageService>('IContactMessageService').to(ContactMessageService);
container.bind<IContactService>('IContactService').to(ContactService);
container.bind<IFeedbackService>('IFeedbackService').to(FeedbackService);
container.bind<IGroupService>('IGroupService').to(GroupService);
container.bind<IMentorService>('IMentorService').to(MentorService);
container.bind<INotificationService>('INotificationService').to(NotificationService);
container.bind<IReviewService>('IReviewService').to(ReviewService);
container.bind<ISkillsService>('ISkillsService').to(SkillsService);
container.bind<ISubcategoryService>('ISubCategoryService').to(SubcategoryService);
container.bind<ITaskService>('ITaskService').to(TaskService);
container.bind<IUserConnectionService>('IUserConnectionService').to(UserConnectionService);

//Middlewares
container.bind<IAuthMiddleware>('IAuthMiddleware').to(AuthMiddleware);

// Bind socket-related classes
container.bind<ISocketService>('ISocketService').to(SocketService);
container.bind<IChatSocketHandler>('IChatSocketHandler').to(ChatSocketHandler);
container.bind<ICallSocketHandler>('ICallSocketHandler').to(CallSocketHandler);
container.bind<IGroupCallSocketHandler>('IGroupCallSocketHandler').to(GroupCallSocketHandler);
container.bind<INotificationSocketHandler>('INotificationSocketHandler').to(NotificationSocketHandler);

//Bind Interface to the controllers
container.bind<IAdminController>('IAdminController').to(AdminController);
container.bind<IAuthController>('IAuthController').to(AuthController);
container.bind<ICallController>('ICallController').to(CallController);
container.bind<ICategoryController>('ICategoryController').to(CategoryController);
container.bind<IChatController>('IChatController').to(ChatController);
container.bind<ICollaborationController>('ICollaborationController').to(CollaborationController);
container.bind<IContactController>('IContactController').to(ContactController);
container.bind<IContactMessageController>('IContactMessageController').to(ContactMessageController);
container.bind<IFeedbackController>('IFeedBackController').to(FeedbackController);
container.bind<IGroupController>('IGroupController').to(GroupController);
container.bind<IMentorController>('IMentorController').to(MentorController);
container.bind<INotificationController>('INotificationController').to(NotificationController);
container.bind<IReviewController>('IReviewController').to(ReviewController);
container.bind<ISkillsController>('ISkillsController').to(SkillsController);
container.bind<ISubcategoryController>('ISubCategoryController').to(SubcategoryController);
container.bind<ITaskController>('ITaskController').to(TaskController);
container.bind<IUserConnectionController>('IUserConnectionController').to(UserConnectionController);


export default container;

