export const AUTH_ROUTES = {
  Register: '/register/signup',
  Login: '/login',
  ForgotPassword: '/register/forgot-password',
  VerifyOTP: '/register/verify-otp',
  ResetPassword: '/register/reset-password',
  GoogleSignup: '/google-signup',
  GoogleLogin: '/google-login',
  GithubSignup: '/github-signup',
  GithubLogin: '/github-login',
  VerifyAdminPasskey: '/verify-admin-passkey',
  RefreshToken: '/refresh-token',
  Logout: '/logout',
  CheckProfile: '/check-profile/:id',
  ProfileDetails: '/profiledetails/:id',
  UpdateUserDetails: '/updateUserDetails/:id',
  GetAllUsers: '/getallusers',
  FetchAllUsers: '/fetchallusers',
  GetUser: '/getuser/:id',
  UpdateUser: '/users/:id',
  UpdatePassword:'/updatePassword/:id',
  BlockUser: '/blockuser/:id',
  UnblockUser: '/unblockuser/:id',
  ChangeRole: '/changerole/:id',
} as const;