export const COLLABORATION_ROUTES = {
  CreateMentorProfile: '/create-mentorprofile',
  GetMentorRequests: '/get-mentor-requests',
  AcceptRequest: '/accept-request/:id',
  RejectRequest: '/reject-request/:id',
  GetUserRequests: '/get-user-requests/:id',
  ProcessPayment: '/process-payment',
  GetCollabDataUser: '/get-collabData-user/:id',
  GetCollabDataMentor: '/get-collabData-mentor/:id',
  CancelAndRefundCollab: '/cancel-and-refund/:collabId',
  GetCollab: '/getCollab/:collabId',
  GetCollabRequest: '/getCollabRequset/:requestId',
  MarkUnavailable: '/markUnavailable/:collabId',
  UpdateTimeslot: '/updateTimeslot/:collabId',
  ApproveTimeSlot: '/approveTimeSlot/:collabId',
  GetLockedSlots: '/locked-slots/:mentorId',
  GetAllMentorRequests: '/getAllRequest',
  GetAllCollabs: '/getAllCollab',
  // RefundCollab: '/refund/:collabId',
  GetReceiptDownload: '/receipt/:collabId',
  DeleteMentorRequest: '/deleteReq/:id'
} as const;